# Generated by Django 2.0.6 on 2019-05-28 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeid', models.IntegerField()),
                ('parentid', models.IntegerField()),
                ('cityName', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='cls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('start', models.DateField()),
                ('progress', models.CharField(max_length=50)),
                ('remark', models.CharField(blank=True, default='无', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('reson', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(blank=True, default='不明', max_length=5, null=True)),
                ('age', models.IntegerField()),
                ('phonenum', models.CharField(max_length=11, unique=True)),
                ('qq', models.CharField(blank=True, default='未留', max_length=15, null=True)),
                ('school', models.CharField(blank=True, default='未留', max_length=30, null=True)),
                ('homeaddr', models.CharField(blank=True, default='未留', max_length=30, null=True)),
                ('addr', models.CharField(max_length=50)),
                ('progress', models.CharField(blank=True, default='未留', max_length=50, null=True)),
                ('job', models.CharField(blank=True, default='未就业', max_length=30, null=True)),
                ('remark', models.CharField(blank=True, default='无', max_length=100, null=True)),
                ('cls', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.cls')),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sex', models.CharField(blank=True, default='不明', max_length=5, null=True)),
                ('phonenum', models.CharField(max_length=11)),
                ('classes', models.ManyToManyField(to='blog.cls')),
            ],
        ),
        migrations.CreateModel(
            name='usrid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='usrinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr', models.CharField(max_length=30)),
                ('pwd', models.CharField(max_length=16)),
                ('uid', models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.usrid')),
            ],
        ),
        migrations.AddField(
            model_name='leave',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.student'),
        ),
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together={('name', 'sex', 'phonenum')},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('name', 'sex', 'age')},
        ),
    ]
