# Generated by Django 2.0.6 on 2019-05-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cls',
            name='teachers',
            field=models.CharField(blank=True, default='无', max_length=30, null=True),
        ),
    ]
